name: Trigger auto deployment for test-nuxt-zimed

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-nuxt-zimed-AutoDeployTrigger-bc0b5296-79a8-4657-9234-350d5c429abf.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTNUXTZIMED_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: piixiieesregistry.azurecr.io
          registryUsername: ${{ secrets.TESTNUXTZIMED_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTNUXTZIMED_REGISTRY_PASSWORD }}
          containerAppName: test-nuxt-zimed
          resourceGroup: Test
          imageToBuild: piixiieesregistry.azurecr.io/test-nuxt-zimed:${{ github.sha }}
          
            

     

